import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ pageName, desc }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a>Home (Next/Link)</a>
        </Link>

        <Link href="/about">
          <a className='active'>About Us (Next/Link)</a>
        </Link>

        <h2>{pageName}</h2>
        <p>{desc}</p>
      </main>
    </div>
  )
}



export async function getServerSideProps(context) {
    return { props: { pageName: "About Page", desc: 'Fetched from server side render' } }
}
  