import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a>Home (Next/Link)</a>
        </Link>

        <Link href="/about">
          <a>About Us (Next/Link)</a>
        </Link>

        <a href="/">Home (a tag)</a>

        <a href="/about">About Us (a tag)</a>
      </main>
    </div>
  )
}
