import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ name, desc }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Link href="/">
          <a className='active'>Home (Next/Link)</a>
        </Link>

        <Link href="/about">
          <a>About Us (Next/Link)</a>
        </Link>
        <h2>{name}</h2>
        <p>{desc}</p>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  return { props: { name: "Trung", pageName: "Home Page", desc: 'Fetched from server side render' } }
}
